### ISSUE TITLE
Feature request: Automatic transistion to Ortographic mode when zoomed out enough

### ISSUE THREAD

**Issue by TotalKrill** [oscrim/bevy_map_camera#4]
Yoyo!

as in f4 Maps, it would be nice, to be able to set a transition limit, so when zoomed out a certain distance from the map (height) it would become an ortographic camera. 

This would enable automatic transition towards a tilemap representation :)

**Comment by nnimoyoefoki** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by oscrim** [comment]
This should be implemented in the app using the camera
